FIRST_COLOR = "#009BD0"
SECOND_COLOR = "#EB6012"
THIRD_COLOR = "#541C65"  # NOVA RESEARCH
FOURTH_COLOR = "#033F85"  # NOVA OCEAN BLUE
FIFTH_COLOR = "#D4007F"  # NOVA STUDENT
SIXTH_COLOR = "#E42313"  # NOVA DAWN RED
SEVENTH_COLOR = "#0069B4" #NOVA AZURE
EIGHT_COLOR = "#68C3CD" #NOVA EMERALD
NINETH_COLOR = "#6EA8B4" #NOVA NAVY
TENTH_COLOR = "#AFD8C1" #NOVA TURQUOISE
ELEVENTH_COLOR = "#D1E2A8" #NOVA LIME
TWELFTH_COLOR = "#FED992" #NOVA SAND YELLOW
THIRTEENTH_COLOR= "#FBBA00" #NOVA AMBER
FOURTEENTH_COLOR = "#EF7D00" #NOVA ORANGE SUNRISE
FIFETEENTH_COLOR = "#A21352" #NOVA BURGUNDY


OFICIAL_COLORS = [FIRST_COLOR,
                  SECOND_COLOR,
                  THIRD_COLOR,
                  FOURTH_COLOR,
                  FIFTH_COLOR,
                  SIXTH_COLOR,
                  SEVENTH_COLOR,
                  EIGHT_COLOR,
                  NINETH_COLOR,
                  TENTH_COLOR,
                  ELEVENTH_COLOR,
                  TWELFTH_COLOR,
                  THIRTEENTH_COLOR,
                  FOURTEENTH_COLOR,
                  FIFETEENTH_COLOR]
